# -*- coding: utf-8 -*-
"""03 Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adaapp/dav-introductionToPandas/blob/master/03%20Titanic.ipynb

# 03 Titanic

![Titanic](https://pmcvariety.files.wordpress.com/2017/04/titanic.jpg?w=1000&h=563&crop=1)
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# %matplotlib inline

"""## Tab separated values"""

titanic = pd.read_csv("https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/titanic.txt", sep='\t')
titanic.head()

"""## Setting ordinal categories"""

titanic.Class = pd.Categorical(titanic.Class, categories=["Crew","3","2","1"])

"""## Seaborn's catplot"""

sns.catplot(data=titanic, x="Sex", hue="Class", kind='count', col="Survived");

from scipy import stats

"""## A non-parametric test"""

stats.mannwhitneyu(titanic.loc[titanic.Survived == "Alive"].Paid.dropna(),
                  titanic.loc[titanic.Survived == "Dead"].Paid.dropna(), alternative='greater')