# -*- coding: utf-8 -*-
"""03b Toytanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adaapp/dav-introductionToPandas/blob/master/03b%20Toytanic.ipynb

# 03b Toytanic

The usual imports
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
# %matplotlib inline

"""Generate n random ages, normally distributed around 20 with standard deviation 3, and round them to the nearest integer:"""

n = 5
ages = np.random.normal(loc=20,scale=3,size=n).round()
ages

"""Generate a list of "Alive" or "Dead", the probability being p:"""

p = 0.5
surv = ["Dead" if np.random.random() > p else "Alive" for _ in range(n)]
surv

"""Make a `pandas` dataframe by giving a dictionary of column headings and data:"""

toytanic = pd.DataFrame(data={'Age': ages,'Survived':surv})
toytanic