# -*- coding: utf-8 -*-
"""04 Baby names.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adaapp/dav-introductionToPandas/blob/master/04%20Baby%20names.ipynb
"""

import pandas as pd

"""## Cleaning a messy csv"""

#g17 = pd.read_csv('2017girlsnames.csv', thousands=',')
g17 = pd.read_csv('https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/2017girlsnames.csv', thousands=',')
g17 = g17.drop(columns="Unnamed: 2").dropna()
g17.Count = g17.Count.astype(int)
g17.head()

"""## Setting an index and sorting on it"""

g17 = g17.set_index(g17.Name).drop(columns=["Name"]).sort_index()
g17

"""## Making a new, constant, column"""

g17["Gender"]="Girl"
g17

"""## Deal with the thousands comma"""

#b17 = pd.read_csv("2017boysnames.csv", thousands=',').drop(columns=["Unnamed: 2"]).dropna()
b17 = pd.read_csv("https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/2017boysnames.csv", thousands=',').drop(columns=["Unnamed: 2"]).dropna()
b17

"""## Converting a column to integer"""

b17.Count = b17.Count.astype(int)
b17

b17 = b17.set_index(b17.Name).drop(columns=["Name"]).sort_index()
b17

b17["Gender"] = "Boy"
b17

"""## Combining data frames - concatenation"""

pd.concat([g17,b17])

names17 = pd.concat([g17,b17])

names17 = names17.sort_index()
names17

#g16 = pd.read_csv("2016girlsnames.csv", thousands=',')
g16 = pd.read_csv("https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/2016girlsnames.csv", thousands=',')
g16.head()

g16 = g16.dropna()
g16.head()

g16.Count = g16.Count.astype(int)
g16

g16 = g16.dropna()
g16.Count = g16.Count.astype(int)
g16

#g15 = pd.read_csv("2015girlsnames.csv", thousands=',')
g15 = pd.read_csv("https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/2015girlsnames.csv", thousands=',')
g15

"""## Drop a single row of data"""

g15.drop(7477)

g15 = g15.drop(columns=["Unnamed: 2"])
g15 = g15.dropna()
g15.Count = g15.Count.astype(int)
g15

"""## Join two dataframes on a common column

What is the difference between an *inner* join and an *outer* join?
"""

pd.merge(g15,g16,how='inner',on='Name',suffixes=["15","16"])

pd.merge(g15,g16,how='outer',on='Name',suffixes=["15","16"])

girls1516 = pd.merge(g15,g16,how='inner',on='Name',suffixes=["15","16"])
girls1516

girls1516 = girls1516.set_index("Name").sort_index()
girls1516

"""## The filter function with like"""

pd.options.display.max_rows = 10000
girls1516.filter(like='-', axis=0)