# -*- coding: utf-8 -*-
"""06a Overview of visualisation libraries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adaapp/dav-introductionToPandas/blob/master/06a%20Overview%20of%20visualisation%20libraries.ipynb
"""

import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.suptitle("Family tree of python plotting packages")
ax.set_xlim(0,300)
ax.set_ylim(0,100)
ax.axison = False
ax.annotate("matplotlib.pyplot",(0,50))
ax.annotate("pandas.plot",(80,50),(155,80),arrowprops=dict(arrowstyle='<-'))
ax.annotate("seaborn",(80,50),(155,50),arrowprops=dict(arrowstyle='<-'))
ax.annotate("bokeh",(80,50),(155,20),arrowprops=dict(arrowstyle='<-'))
ax.annotate("holoviews",(185,20),(255,50),arrowprops=dict(arrowstyle='<-'))
ax.annotate("chartify",(185,20),(255,20),arrowprops=dict(arrowstyle='<-'))
ax.annotate("plotly",(25,75))
ax.annotate("dash",(50,75),(95,90),arrowprops=dict(arrowstyle='<-'));

"""- [matplotlib](https://matplotlib.org/)
    - The oldest and most developed library
    - Highly flexible
    - Steep learning curve
    - Two distinct styles of use which can be confusing because different examples might use different approaches
    - Can be used to draw pretty much anything not just graphs

- [pandas plotting](https://pandas.pydata.org/pandas-docs/stable/visualization.html)
    - Built on matplotlib.pyplot
    - Plot directly from a dataframe
    - Okay defaults but often need to access underlying pyplot anyway

- [seaborn](https://seaborn.pydata.org/)
    - Also built on matplotlib.pyplot but better aesthetics
    - Easy to create [composite plots with multiple factors](https://seaborn.pydata.org/examples/index.html#example-gallery)
    - Automatically builds in things like regression lines with confidence intervals
    - Static, though does work well with jupyter's interactive widgets

- [bokeh](https://bokeh.pydata.org/en/latest/)
    - Again, built on matplotlib.pyplot
    - Easy to create very interactive plots
    - Works best as a live web app
    - Doesn't always play well in jupyter notebooks

- [holoviews](http://holoviews.org/)
    - Built on bokeh for interaction, but can also work directly with pyplot for static plots
    - Describe the semantics of the data and let holoviews decide what to do with it

- [chartify](https://github.com/spotify/chartify)
    - Spotify's take on bokeh
    - Intuitive workflow
    - Good choice of defaults
    - Consistent naming of parts

- [plotly](https://github.com/plotly/plotly.py/blob/master/README.md)
    - Not built on pyplot
    - Hands off the plotting to a javascript library
- [dash](https://plot.ly/)
    - Built on plotly
    - Good for building data dashboards
    - Has to run as a web app
"""