# -*- coding: utf-8 -*-
"""09 The World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/adaapp/dav-introductionToPandas/blob/master/09%20The%20World.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

world = pd.read_csv("https://raw.githubusercontent.com/adaapp/dav-introductionToPandas/master/world.csv")
world.head()

world.set_index("country").drop(columns="no")

world = world.set_index("country").drop(columns="no")

"""## Seaborn relplot

This is a *facet* plot. Here we tell it to group the data by subregions in three columns.
"""

sns.relplot(data=world, x="physician_density", y="birthrate", col="subregion", col_wrap=3)

"""## Selecting numerical columns

We can use `select_dtypes` to get only columns containing certain kinds of data, in this case floats and integers - ie numeric.
"""

world.select_dtypes(include=['float64','int64'])

"""## Seaborn pairplot

We can give that numeric data to seaborn's `pairplot` function to look for relationships between any pair of variables, and as a bonus see the distribution of each variable in a histogram.
"""

sns.pairplot(world.select_dtypes(include=['float64','int64']).dropna())

"""## Introduction to geopandas"""

import geopandas

"""`geopandas` has some built-in maps. They're really just dataframes with some drawing information attached."""

gp_world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
gp_world

"""### How to get your index back into a column"""

world = world.reset_index()

"""## Merging on a common column with different names"""

gp_merged = gp_world.merge(world,right_on="country", left_on="name")
gp_merged

"""## Drawing a map

(or choropleth diagram)
"""

gp_merged.dropna().plot(column="gdp")